/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Client.Facade.GameController;
import Client.Model.Game;
import Client.Model.Player;
import java.awt.Color;
import java.io.IOException;
import java.util.Iterator;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author jacy Marques
 */
public class Game2 extends javax.swing.JFrame {

    private GameController client;
    private String atual;
    private Player p;
    private ThreadJogo aux;
    private boolean roleta = false;
    private int r;
    

    /**
     * Creates new form ModoJogo
     */
    public Game2(GameController client) throws IOException, ClassNotFoundException {
        this.client = client;
        initComponents();
        setVisible(false);
        while (!client.isGameSetted());
        rodada.setText("Iniciando");
        setVisible(true);
        p = client.getPlayer();
        aux = new ThreadJogo(p, this);
        Thread t = new Thread(aux);
        t.start();
        
    }

    public void pegarLetra(JButton button) {
        if(roleta){
        
        button.setEnabled(false);
        atual = button.getText();

        try {
            game();
            roleta = false;
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(Game2.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
        else if(r != Game.SKIP_PLAYER || r != Game.RESET_VALUE){
           JOptionPane.showMessageDialog(null, "Rode a roleta");
        }
    }

    public void game() throws IOException, ClassNotFoundException {

        if (!p.isGameFinished()) {
            if (p.isMyTurn() && !p.isRoundFinished()) {
                    char c = atual.toUpperCase().charAt(0);
                    int number = p.tryCharacter(c);
                    getWord().setText(p.getWord());
                    //System.out.println("\nAcertou " + number + " letras");
            }
            else if(r == Game.RESET_VALUE){
                    JOptionPane.showMessageDialog(null, "Perdeu Tudo!");
                } 
                
            else {
                    JOptionPane.showMessageDialog(null, "Passou a vez!");
                }

            if (p.isRoundFinished()) {
                JOptionPane.showMessageDialog(null, "Palavra era: " + p.getWord());
                p.nextRound();
                carregarBotao();
            }

            if (p.isGameFinished()) {
                p.sendResult();
                //p.getRankingInfo();
                setVisible(false);
                try{
                    
                    if( Integer.parseInt(pv1.getText()) < Integer.parseInt(pv2.getText())){
                        JOptionPane.showMessageDialog(null, "Você Venceu!");
                    }else{
                        JOptionPane.showMessageDialog(null, "Você Perdeu!");
                    }
                   
                p.sendResult();
                new Ranking(client);
                
                }catch(Exception e){
                    new Home();
                }
            }
        }
    }

    public void carregarBotao() {
        A.setEnabled(true);
        B.setEnabled(true);
        C.setEnabled(true);
        D.setEnabled(true);
        E.setEnabled(true);
        F.setEnabled(true);
        G.setEnabled(true);
        H.setEnabled(true);
        I.setEnabled(true);
        J.setEnabled(true);
        K.setEnabled(true);
        L.setEnabled(true);
        M.setEnabled(true);
        N.setEnabled(true);
        O.setEnabled(true);
        P.setEnabled(true);
        Q.setEnabled(true);
        R.setEnabled(true);
        S.setEnabled(true);
        T.setEnabled(true);
        U.setEnabled(true);
        V.setEnabled(true);
        W.setEnabled(true);
        X.setEnabled(true);
        Y.setEnabled(true);
        Z.setEnabled(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        A = new javax.swing.JButton();
        B = new javax.swing.JButton();
        C = new javax.swing.JButton();
        D = new javax.swing.JButton();
        J = new javax.swing.JButton();
        E = new javax.swing.JButton();
        F = new javax.swing.JButton();
        G = new javax.swing.JButton();
        H = new javax.swing.JButton();
        I = new javax.swing.JButton();
        K = new javax.swing.JButton();
        L = new javax.swing.JButton();
        M = new javax.swing.JButton();
        N = new javax.swing.JButton();
        O = new javax.swing.JButton();
        P = new javax.swing.JButton();
        Q = new javax.swing.JButton();
        R = new javax.swing.JButton();
        S = new javax.swing.JButton();
        T = new javax.swing.JButton();
        U = new javax.swing.JButton();
        V = new javax.swing.JButton();
        W = new javax.swing.JButton();
        X = new javax.swing.JButton();
        Y = new javax.swing.JButton();
        Z = new javax.swing.JButton();
        click = new javax.swing.JButton();
        roletaImage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        dica = new javax.swing.JLabel();
        painelNome = new javax.swing.JPanel();
        word = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        pv2 = new javax.swing.JLabel();
        pv1 = new javax.swing.JLabel();
        rodada = new javax.swing.JLabel();
        valorLetra = new javax.swing.JLabel();
        suavez = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jLabel3.setText("jLabel3");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        A.setText("A");
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });
        jPanel2.add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 45, -1));

        B.setText("B");
        B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActionPerformed(evt);
            }
        });
        jPanel2.add(B, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 45, -1));

        C.setText("C");
        C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CActionPerformed(evt);
            }
        });
        jPanel2.add(C, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 45, -1));

        D.setText("D");
        D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DActionPerformed(evt);
            }
        });
        jPanel2.add(D, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 45, -1));

        J.setText("J");
        J.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JActionPerformed(evt);
            }
        });
        jPanel2.add(J, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 45, -1));

        E.setText("E");
        E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EActionPerformed(evt);
            }
        });
        jPanel2.add(E, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 45, -1));

        F.setText("F");
        F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FActionPerformed(evt);
            }
        });
        jPanel2.add(F, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 45, -1));

        G.setText("G");
        G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GActionPerformed(evt);
            }
        });
        jPanel2.add(G, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 45, -1));

        H.setText("H");
        H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HActionPerformed(evt);
            }
        });
        jPanel2.add(H, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 45, -1));

        I.setText("I");
        I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IActionPerformed(evt);
            }
        });
        jPanel2.add(I, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, 45, -1));

        K.setText("K");
        K.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KActionPerformed(evt);
            }
        });
        jPanel2.add(K, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 45, -1));

        L.setText("L");
        L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LActionPerformed(evt);
            }
        });
        jPanel2.add(L, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 45, -1));

        M.setText("M");
        M.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MActionPerformed(evt);
            }
        });
        jPanel2.add(M, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 45, -1));

        N.setText("N");
        N.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NActionPerformed(evt);
            }
        });
        jPanel2.add(N, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 45, -1));

        O.setText("O");
        O.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OActionPerformed(evt);
            }
        });
        jPanel2.add(O, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 45, -1));

        P.setText("P");
        P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PActionPerformed(evt);
            }
        });
        jPanel2.add(P, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 45, -1));

        Q.setText("Q");
        Q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QActionPerformed(evt);
            }
        });
        jPanel2.add(Q, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 45, -1));

        R.setText("R");
        R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RActionPerformed(evt);
            }
        });
        jPanel2.add(R, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 45, -1));

        S.setText("S");
        S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SActionPerformed(evt);
            }
        });
        jPanel2.add(S, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 45, -1));

        T.setText("T");
        T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TActionPerformed(evt);
            }
        });
        jPanel2.add(T, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 45, -1));

        U.setText("U");
        U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UActionPerformed(evt);
            }
        });
        jPanel2.add(U, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 45, -1));

        V.setText("V");
        V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VActionPerformed(evt);
            }
        });
        jPanel2.add(V, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 45, -1));

        W.setText("W");
        W.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WActionPerformed(evt);
            }
        });
        jPanel2.add(W, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 45, -1));

        X.setText("X");
        X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XActionPerformed(evt);
            }
        });
        jPanel2.add(X, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 45, -1));

        Y.setText("Y");
        Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YActionPerformed(evt);
            }
        });
        jPanel2.add(Y, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 45, -1));

        Z.setText("Z");
        Z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZActionPerformed(evt);
            }
        });
        jPanel2.add(Z, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 45, -1));

        click.setFont(new java.awt.Font("Cantarell", 3, 18)); // NOI18N
        click.setText("Clique");
        click.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickActionPerformed(evt);
            }
        });
        jPanel2.add(click, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 80, 20));

        roletaImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/oie_transparent.png"))); // NOI18N
        jPanel2.add(roletaImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        dica.setText("Dica: Primeira palavra não tem dica");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dica)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dica)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 350, 70));

        word.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        word.setText("_ _ _ _ _ _ _ _ ");

        javax.swing.GroupLayout painelNomeLayout = new javax.swing.GroupLayout(painelNome);
        painelNome.setLayout(painelNomeLayout);
        painelNomeLayout.setHorizontalGroup(
            painelNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelNomeLayout.setVerticalGroup(
            painelNomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelNomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(word, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(painelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 190, 50));

        p2.setBackground(new java.awt.Color(255, 0, 51));
        p2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        p2.setText(" 2");
        p2.setOpaque(true);
        jPanel2.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 90, 20));

        p1.setBackground(new java.awt.Color(255, 0, 51));
        p1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        p1.setText(" 1");
        p1.setOpaque(true);
        jPanel2.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 80, 20));

        pv2.setText("0");
        pv2.setOpaque(true);
        jPanel2.add(pv2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 70, 20));

        pv1.setText("0");
        pv1.setOpaque(true);
        jPanel2.add(pv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 70, 20));

        rodada.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        rodada.setText("Rodada Atual");
        jPanel2.add(rodada, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 190, -1));

        valorLetra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        valorLetra.setText("Cada Letra Vale: ");
        jPanel2.add(valorLetra, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        suavez.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        suavez.setText("vez");
        suavez.setOpaque(true);
        jPanel2.add(suavez, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/background.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IActionPerformed
        pegarLetra(getI());
    }//GEN-LAST:event_IActionPerformed

    private void WActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WActionPerformed
        pegarLetra(getW());
    }//GEN-LAST:event_WActionPerformed

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        pegarLetra(getA());
    }//GEN-LAST:event_AActionPerformed

    private void BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActionPerformed
        pegarLetra(getB());
    }//GEN-LAST:event_BActionPerformed

    private void CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CActionPerformed
        pegarLetra(getC());
    }//GEN-LAST:event_CActionPerformed

    private void DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DActionPerformed
        pegarLetra(getD());
    }//GEN-LAST:event_DActionPerformed

    private void EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EActionPerformed
        pegarLetra(getE());
    }//GEN-LAST:event_EActionPerformed

    private void FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FActionPerformed
        pegarLetra(getF());        // TODO add your handling code here:
    }//GEN-LAST:event_FActionPerformed

    private void GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GActionPerformed
        pegarLetra(getG());        // TODO add your handling code here:
    }//GEN-LAST:event_GActionPerformed

    private void HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HActionPerformed
        pegarLetra(getH());        // TODO add your handling code here:
    }//GEN-LAST:event_HActionPerformed

    private void JActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JActionPerformed
        pegarLetra(getJ());        // TODO add your handling code here:
    }//GEN-LAST:event_JActionPerformed

    private void KActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KActionPerformed
        pegarLetra(getK());        // TODO add your handling code here:
    }//GEN-LAST:event_KActionPerformed

    private void LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LActionPerformed
        pegarLetra(getL());        // TODO add your handling code here:
    }//GEN-LAST:event_LActionPerformed

    private void MActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MActionPerformed
        pegarLetra(getM());        // TODO add your handling code here:
    }//GEN-LAST:event_MActionPerformed

    private void NActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NActionPerformed
        pegarLetra(getN());        // TODO add your handling code here:
    }//GEN-LAST:event_NActionPerformed

    private void OActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OActionPerformed
        pegarLetra(getO());        // TODO add your handling code here:
    }//GEN-LAST:event_OActionPerformed

    private void PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PActionPerformed
        pegarLetra(getP());        // TODO add your handling code here:
    }//GEN-LAST:event_PActionPerformed

    private void QActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QActionPerformed
        pegarLetra(getQ());        // TODO add your handling code here:
    }//GEN-LAST:event_QActionPerformed

    private void RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RActionPerformed
        pegarLetra(getR());        // TODO add your handling code here:
    }//GEN-LAST:event_RActionPerformed

    private void SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SActionPerformed
        pegarLetra(getS());        // TODO add your handling code here:
    }//GEN-LAST:event_SActionPerformed

    private void TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TActionPerformed
        pegarLetra(getT());        // TODO add your handling code here:
    }//GEN-LAST:event_TActionPerformed

    private void UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UActionPerformed
        pegarLetra(getU());        // TODO add your handling code here:
    }//GEN-LAST:event_UActionPerformed

    private void VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VActionPerformed
        pegarLetra(getV());        // TODO add your handling code here:
    }//GEN-LAST:event_VActionPerformed

    private void XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XActionPerformed
        pegarLetra(X);        // TODO add your handling code here:
    }//GEN-LAST:event_XActionPerformed

    private void YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YActionPerformed
        pegarLetra(Y);        // TODO add your handling code here:
    }//GEN-LAST:event_YActionPerformed

    private void ZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZActionPerformed
        pegarLetra(getZ());        // TODO add your handling code here:
    }//GEN-LAST:event_ZActionPerformed

    private void clickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickActionPerformed
        if(!roleta && p.isMyTurn()){
            try {
                r = p.roullete();                    
                if (r != Game.SKIP_PLAYER && r != Game.RESET_VALUE) {
                    aux.setValor(r);
                    roleta = true;
                }else if(r == Game.RESET_VALUE){
                    JOptionPane.showMessageDialog(null, "Perdeu Tudo!");
                }else if(r == Game.SKIP_PLAYER){
                    JOptionPane.showMessageDialog(null, "Passou a Vez!");
                }
                    
            } catch (IOException ex) {
                Logger.getLogger(Game2.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
            
        else{
            JOptionPane.showMessageDialog(null, "Não é sua vez");
        }
    }//GEN-LAST:event_clickActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A;
    private javax.swing.JButton B;
    private javax.swing.JButton C;
    private javax.swing.JButton D;
    private javax.swing.JButton E;
    private javax.swing.JButton F;
    private javax.swing.JButton G;
    private javax.swing.JButton H;
    private javax.swing.JButton I;
    private javax.swing.JButton J;
    private javax.swing.JButton K;
    private javax.swing.JButton L;
    private javax.swing.JButton M;
    private javax.swing.JButton N;
    private javax.swing.JButton O;
    private javax.swing.JButton P;
    private javax.swing.JButton Q;
    private javax.swing.JButton R;
    private javax.swing.JButton S;
    private javax.swing.JButton T;
    private javax.swing.JButton U;
    private javax.swing.JButton V;
    private javax.swing.JButton W;
    private javax.swing.JButton X;
    private javax.swing.JButton Y;
    private javax.swing.JButton Z;
    private javax.swing.JButton click;
    private javax.swing.JLabel dica;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JPanel painelNome;
    private javax.swing.JLabel pv1;
    private javax.swing.JLabel pv2;
    private javax.swing.JLabel rodada;
    private javax.swing.JLabel roletaImage;
    private javax.swing.JLabel suavez;
    private javax.swing.JLabel valorLetra;
    private javax.swing.JLabel word;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the dica
     */
    public javax.swing.JLabel getDica() {
        return dica;
    }

    /**
     * @return the rodada
     */
    public javax.swing.JLabel getRodada() {
        return rodada;
    }

    /**
     * @return the word
     */
    public javax.swing.JLabel getWord() {
        return word;
    }

    public javax.swing.JLabel getValorLetra() {
        return valorLetra;
    }

    /**
     * @return the A
     */
    public javax.swing.JButton getA() {
        return A;
    }

    /**
     * @return the B
     */
    public javax.swing.JButton getB() {
        return B;
    }

    /**
     * @return the C
     */
    public javax.swing.JButton getC() {
        return C;
    }

    /**
     * @return the D
     */
    public javax.swing.JButton getD() {
        return D;
    }

    /**
     * @return the E
     */
    public javax.swing.JButton getE() {
        return E;
    }

    /**
     * @return the F
     */
    public javax.swing.JButton getF() {
        return F;
    }

    /**
     * @return the G
     */
    public javax.swing.JButton getG() {
        return G;
    }

    /**
     * @return the H
     */
    public javax.swing.JButton getH() {
        return H;
    }

    /**
     * @return the I
     */
    public javax.swing.JButton getI() {
        return I;
    }

    /**
     * @return the J
     */
    public javax.swing.JButton getJ() {
        return J;
    }

    /**
     * @return the K
     */
    public javax.swing.JButton getK() {
        return K;
    }

    /**
     * @return the L
     */
    public javax.swing.JButton getL() {
        return L;
    }

    /**
     * @return the M
     */
    public javax.swing.JButton getM() {
        return M;
    }

    /**
     * @return the N
     */
    public javax.swing.JButton getN() {
        return N;
    }

    /**
     * @return the O
     */
    public javax.swing.JButton getO() {
        return O;
    }

    public javax.swing.JButton getP() {
        return P;
    }

    /**
     * @return the Q
     */
    public javax.swing.JButton getQ() {
        return Q;
    }

    /**
     * @return the R
     */
    public javax.swing.JButton getR() {
        return R;
    }

    /**
     * @return the S
     */
    public javax.swing.JButton getS() {
        return S;
    }

    /**
     * @return the T
     */
    public javax.swing.JButton getT() {
        return T;
    }

    /**
     * @return the U
     */
    public javax.swing.JButton getU() {
        return U;
    }

    /**
     * @return the V
     */
    public javax.swing.JButton getV() {
        return V;
    }

    /**
     * @return the W
     */
    public javax.swing.JButton getW() {
        return W;
    }

    public javax.swing.JButton getx() {
        return X;
    }

    public javax.swing.JButton gety() {
        return Y;
    }

    /**
     * @return the Z
     */
    public javax.swing.JButton getZ() {
        return Z;
    }
    
    public javax.swing.JLabel getP1() {
        return p1;
    }
    
    public javax.swing.JLabel getVez() {
        return suavez;
    }
    
    public javax.swing.JLabel getP2() {
        return p2;
    }
    
    public javax.swing.JLabel getPontuacao1() {
        return pv1;
    }
    
    public javax.swing.JLabel getPontuacao2() {
        return pv2;
    }
    
    public javax.swing.JLabel getValor() {
        return valorLetra;
    }
}
