/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

import Client.Facade.GameController;
import Client.Model.Client;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jacy Marques
 */
public class ModoJogo extends javax.swing.JFrame {

    /**
     * Creates new form ModoJogo
     */
    private GameController client;
    private Game2 jogo;
    private Game3 jogo3;
    private AguardandoOponente aguardar;
    
    public ModoJogo(GameController client) {
        initComponents();
        this.client = client;
        setVisible(true);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sair = new javax.swing.JButton();
        ranking = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dupla = new javax.swing.JButton();
        trio = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jLabel3.setText("jLabel3");

        jLabel5.setText("jLabel5");

        sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sair.png"))); // NOI18N

        ranking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ranking.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/modo.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        dupla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dupla.png"))); // NOI18N
        dupla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duplaActionPerformed(evt);
            }
        });
        jPanel2.add(dupla, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 130, 40));

        trio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/trio.png"))); // NOI18N
        trio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trioActionPerformed(evt);
            }
        });
        jPanel2.add(trio, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 110, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/background.png"))); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void duplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duplaActionPerformed
        try {
            client.waitForPlayers(2);
            setVisible(false);
            while(!this.client.isGameSetted());
            jogo = new Game2(client);
            
            
            
            
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(ModoJogo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_duplaActionPerformed

    private void trioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trioActionPerformed
        try {
            client.waitForPlayers(3);
            setVisible(false);
            while(!this.client.isGameSetted());
            jogo3 = new Game3(client);
            
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(ModoJogo.class.getName()).log(Level.SEVERE, null, ex);
        }
                    
    }//GEN-LAST:event_trioActionPerformed

    /**
     * @param args the command line arguments
     */
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dupla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton ranking;
    private javax.swing.JButton sair;
    private javax.swing.JButton trio;
    // End of variables declaration//GEN-END:variables
}
